-- Q1. Find the total sales by country_id and channel_desc for the US and GB through the Internet and direct sales in September 2000 and October 2000 using ROLL-UP Extension. The query should return the following:
-- 1. The aggregation rows that would be produced by GROUP BY
-- 2. The First-level subtotals aggregating across country_iso_code for each combination of channel_desc and calendar_month.
-- 3. Second-level subtotals aggregating across calendar_month_desc and country_iso_code for each channel_desc value.
-- 4. A grand total row.

SELECT COUNTRY_ISO_CODE, CHANNEL_DESC, CALENDAR_MONTH_DESC, TO_CHAR(SUM(AMOUNT_SOLD), '9,999,999') AS TOTAL_SALES$
FROM SALES S
         JOIN CHANNELS C ON S.CHANNEL_ID = C.CHANNEL_ID
         JOIN CUSTOMERS CU ON S.CUST_ID = CU.CUST_ID
         JOIN COUNTRIES CO ON CU.COUNTRY_ID = CO.COUNTRY_ID
         JOIN TIMES T ON T.TIME_ID = S.TIME_ID
WHERE COUNTRY_ISO_CODE IN ('US', 'GB')
  AND CHANNEL_DESC IN ('Internet', 'Direct Sales')
  AND CALENDAR_MONTH_DESC IN ('2000-09', '2000-10')
GROUP BY ROLLUP (COUNTRY_ISO_CODE, CHANNEL_DESC, CALENDAR_MONTH_DESC);

-- Q2. Find the total sales by country_iso_code and channel_desc for the US and GB through the
-- Internet and direct sales in September 2000 and October 2009 using CUBE aggregation across
-- three dimensions- channel_desc, calendar_month_desc, countries. country_iso_code.

SELECT COUNTRY_ISO_CODE, CHANNEL_DESC, CALENDAR_MONTH_DESC, TO_CHAR(SUM(AMOUNT_SOLD), '9,999,999') AS TOTAL_SALES$
FROM SALES S
         JOIN CHANNELS C ON S.CHANNEL_ID = C.CHANNEL_ID
         JOIN CUSTOMERS CU ON S.CUST_ID = CU.CUST_ID
         JOIN COUNTRIES CO ON CU.COUNTRY_ID = CO.COUNTRY_ID
         JOIN TIMES T ON T.TIME_ID = S.TIME_ID
WHERE COUNTRY_ISO_CODE IN ('US', 'GB')
  AND CHANNEL_DESC IN ('Internet', 'Direct Sales')
  AND CALENDAR_MONTH_DESC IN ('2000-09', '2000-10')
GROUP BY CUBE (COUNTRY_ISO_CODE, CHANNEL_DESC, CALENDAR_MONTH_DESC);

-- Q3. Find the total sales by country_iso and channel_desc for the US and France through the
-- Internet and direct sales in September 2000

SELECT COUNTRY_ISO_CODE, CHANNEL_DESC, CALENDAR_MONTH_DESC, TO_CHAR(SUM(AMOUNT_SOLD), '9,999,999') AS TOTAL_SALES$
FROM SALES S
         JOIN CHANNELS C ON S.CHANNEL_ID = C.CHANNEL_ID
         JOIN CUSTOMERS CU ON S.CUST_ID = CU.CUST_ID
         JOIN COUNTRIES CO ON CU.COUNTRY_ID = CO.COUNTRY_ID
         JOIN TIMES T ON T.TIME_ID = S.TIME_ID
WHERE COUNTRY_ISO_CODE IN ('US', 'FR')
  AND CHANNEL_DESC IN ('Internet', 'Direct Sales')
  AND CALENDAR_MONTH_DESC IN ('2000-09')
-- GROUP BY CHANNEL_DESC, ROLLUP ( COUNTRY_ISO_CODE, CALENDAR_MONTH_DESC); -- PARTIAL ROLLUP
GROUP BY CHANNEL_DESC, CUBE ( COUNTRY_ISO_CODE, CALENDAR_MONTH_DESC);
-- PARTIAL CUBE

-- Use 'GROUPING SETS' to create a set of mask columns for the result set of Q1.
--  Create grouping on channel_desc and name it as CH
--  Create grouping calendar_month_desc and name it as MO
--  Create grouping on country_iso_code and name it as CO

SELECT COUNTRY_ISO_CODE,
       CHANNEL_DESC,
       CALENDAR_MONTH_DESC,
       TO_CHAR(SUM(AMOUNT_SOLD), '9,999,999') AS TOTAL_SALES$,
       GROUPING(COUNTRY_ISO_CODE)             AS CO,
       GROUPING(CHANNEL_DESC)                 AS CH,
       GROUPING(CALENDAR_MONTH_DESC)          AS MO
FROM SALES
         JOIN CHANNELS C ON SALES.CHANNEL_ID = C.CHANNEL_ID
         JOIN CUSTOMERS CU ON SALES.CUST_ID = CU.CUST_ID
         JOIN COUNTRIES CO ON CU.COUNTRY_ID = CO.COUNTRY_ID
         JOIN TIMES T ON T.TIME_ID = SALES.TIME_ID
WHERE COUNTRY_ISO_CODE IN ('US', 'GB')
  AND CHANNEL_DESC IN ('Internet', 'Direct Sales')
  AND CALENDAR_MONTH_DESC IN ('2000-09', '2000-10')
GROUP BY GROUPING SETS
    (
    (CHANNEL_DESC, COUNTRY_ISO_CODE, CALENDAR_MONTH_DESC),
    ( CHANNEL_DESC, COUNTRY_ISO_CODE),
    ( CHANNEL_DESC, CALENDAR_MONTH_DESC),
    ( COUNTRY_ISO_CODE, CALENDAR_MONTH_DESC),
    ( CHANNEL_DESC),
    ( COUNTRY_ISO_CODE),
    ( CALENDAR_MONTH_DESC),
    ()
    );

-- USING ROLLUP FOR LOCATION HIERARCHY
SELECT COUNTRY_REGION, COUNTRY_SUBREGION, COUNTRY_NAME, SUM(COUNTRY_REGION_ID) AS COUNTRY_REGION_ID
FROM COUNTRIES C
         JOIN SALES S ON C.COUNTRY_ID = S.COUNTRY_ID
GROUP BY ROLLUP (COUNTRY_REGION, COUNTRY_SUBREGION, COUNTRY_NAME);


SELECT COUNTRY_ISO_CODE, CHANNEL_DESC, CALENDAR_MONTH_DESC, TO_CHAR(SUM(AMOUNT_SOLD), '9,999,999') AS TOTAL_SALES$
FROM CUSTOMERS C
         JOIN SALES S ON C.CUST_ID = S.CUST_ID
         JOIN CHANNELS CH ON S.CHANNEL_ID = CH.CHANNEL_ID
         JOIN COUNTRIES CO ON C.COUNTRY_ID = CO.COUNTRY_ID
         JOIN TIMES T ON S.TIME_ID = T.TIME_ID
WHERE COUNTRY_ISO_CODE IN ('US', 'GB')
  AND CHANNEL_DESC IN ('Internet', 'Direct Sales')
  AND CALENDAR_MONTH_DESC IN ('2000-09', '2000-10')
GROUP BY ROLLUP (COUNTRY_ISO_CODE, CHANNEL_DESC, CALENDAR_MONTH_DESC);

-- USING CUBE FOR LOCATION HIERARCHY
SELECT COUNTRY_ISO_CODE, CHANNEL_DESC, CALENDAR_MONTH_DESC, TO_CHAR(SUM(AMOUNT_SOLD), '9,999,999') AS TOTAL_SALES$
FROM CUSTOMERS C
         JOIN SALES S ON C.CUST_ID = S.CUST_ID
         JOIN CHANNELS CH ON S.CHANNEL_ID = CH.CHANNEL_ID
         JOIN COUNTRIES CO ON C.COUNTRY_ID = CO.COUNTRY_ID
         JOIN TIMES T ON S.TIME_ID = T.TIME_ID
WHERE COUNTRY_ISO_CODE IN ('US', 'GB')
  AND CHANNEL_DESC IN ('Internet', 'Direct Sales')
  AND CALENDAR_MONTH_DESC IN ('2000-09', '2000-10')
GROUP BY CUBE (COUNTRY_ISO_CODE, CHANNEL_DESC, CALENDAR_MONTH_DESC);
