-- CREATE A TEST TABLE WITH INTERVAL PARTITIONING
CREATE TABLE TEST
(
    ID        INT,
    LAST_NAME VARCHAR(20),
    SALARY    DECIMAL(10, 2)
)
    PARTITION BY RANGE (SALARY) INTERVAL (1000)
(
    PARTITION P0 VALUES LESS THAN (1000),
    PARTITION P1 VALUES LESS THAN (2000),
    PARTITION P2 VALUES LESS THAN (3000)
);

-- INSERT SOME DATA
INSERT INTO TEST
VALUES (1, 'Smith', 1290);
INSERT INTO TEST
VALUES (2, 'Jones', 2084);
INSERT INTO TEST
VALUES (3, 'Brown', 3593);

-- QUERY THE TABLE
SELECT *
FROM TEST;

-- ADDING NEW DATA TO THE TABLE
INSERT INTO TEST
VALUES (4, 'Shan', 7823);

-- QUERY THE PARTITIONS
SELECT *
FROM TEST PARTITION (P0);

SELECT *
FROM TEST PARTITION (P1);

SELECT *
FROM TEST PARTITION (P2);

-- SELECT *
-- FROM TEST PARTITION (P4);
-- P4 DOES NOT EXIST BUT IT IS NOT AN ERROR.

DROP TABLE TEST;