-- CREATE A SAMPLE TEST TABLE WITH LIST PARTITIONING
CREATE TABLE TEST_LIST
(
    ID   INT,
    NAME VARCHAR(20)
)
    PARTITION BY LIST
(
    ID
)
(
    PARTITION P1 VALUES (1, 2, 3, 4, 5),
    PARTITION P2 VALUES (6, 7, 8, 9, 10)
);

-- INSERT SOME DATA INTO THE TABLE
INSERT INTO TEST_LIST
VALUES (1, 'ONE');
INSERT INTO TEST_LIST
VALUES (2, 'TWO');
INSERT INTO TEST_LIST
VALUES (3, 'THREE');

INSERT INTO TEST_LIST
VALUES (6, 'SIX');
INSERT INTO TEST_LIST
VALUES (7, 'SEVEN');
INSERT INTO TEST_LIST
VALUES (8, 'EIGHT');

-- QUERYING THE TABLE
SELECT *
FROM TEST_LIST;

-- QUERYING THE TABLE WITH A PARTITION SPECIFICATION
SELECT *
FROM TEST_LIST PARTITION (P1);

SELECT *
FROM TEST_LIST PARTITION (P2);

DROP TABLE TEST_LIST;