-- CREATE TIME TABLE
CREATE TABLE TIMES
(
    TIME_ID      NUMBER PRIMARY KEY,
    YEAR         NUMBER,
    QUARTER      NUMBER,
    MONTH        VARCHAR2(20),
    WEEK         NUMBER,
    DAY          NUMBER,
    HOLIDAY_FLAG NUMBER(1)
);

-- CREATE LOCATION TABLE
CREATE TABLE LOCATIONS
(
    LOC_ID  NUMBER PRIMARY KEY NOT NULL,
    COUNTRY VARCHAR(50)        NOT NULL,
    STATE   VARCHAR(50),
    CITY    VARCHAR(50)        NOT NULL
);

-- CREATE PRODUCT TABLE
CREATE TABLE PRODUCTS
(
    PROD_ID   INTEGER PRIMARY KEY,
    PROD_NAME VARCHAR(255),
    CATEGORY  VARCHAR(255),
    PRICE     DECIMAL(10, 2)
);

-- CREATING SALES TABLE WITH CONSTRAINTS
CREATE TABLE SALES
(
    PROD_ID    INTEGER,
    TIME_ID    INTEGER,
    LOC_ID     INTEGER,
    UNITS_SOLD INTEGER,
    CONSTRAINT fk_prod_id FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS (PROD_ID),
    CONSTRAINT fk_time_id FOREIGN KEY (TIME_ID) REFERENCES TIMES (TIME_ID),
    CONSTRAINT fk_loc_id FOREIGN KEY (LOC_ID) REFERENCES LOCATIONS (LOC_ID)
);

-- ADDING DATA TO TIMES TABLE


-- ADDING RANDOM DATA TO SALES TABLE
INSERT ALL INTO SALES (PROD_ID, TIME_ID, LOC_ID, UNITS_SOLD)
VALUES (1, 1, 1, 10)
INTO SALES
VALUES (2, 2, 1, 15)
INTO SALES
VALUES (3, 3, 2, 8)
INTO SALES
VALUES (4, 4, 2, 12)
INTO SALES
VALUES (5, 5, 3, 20)
INTO SALES
VALUES (6, 6, 3, 6)
INTO SALES
VALUES (7, 7, 4, 18)
INTO SALES
VALUES (8, 8, 4, 4)
INTO SALES
VALUES (9, 9, 5, 14)
INTO SALES
VALUES (10, 10, 5, 16)
SELECT *
FROM DUAL;

SELECT *
FROM SALES;
