-- CREATE TIME TABLE
CREATE TABLE TIMES
(
    TIME_ID      NUMBER PRIMARY KEY,
    YEAR         NUMBER,
    QUARTER      NUMBER,
    MONTH        VARCHAR2(20),
    WEEK         NUMBER,
    DAY          NUMBER,
    HOLIDAY_FLAG NUMBER(1)
);

-- CREATE LOCATION TABLE
CREATE TABLE LOCATIONS
(
    LOC_ID  NUMBER PRIMARY KEY NOT NULL,
    COUNTRY VARCHAR(50)        NOT NULL,
    STATE   VARCHAR(50),
    CITY    VARCHAR(50)        NOT NULL
);

-- CREATE PRODUCT TABLE
CREATE TABLE PRODUCTS
(
    PROD_ID   INTEGER PRIMARY KEY,
    PROD_NAME VARCHAR(255),
    CATEGORY  VARCHAR(255),
    PRICE     DECIMAL(10, 2)
);

-- CREATING SALES TABLE WITH CONSTRAINTS
CREATE TABLE SALES
(
    PROD_ID    INTEGER,
    TIME_ID    INTEGER,
    LOC_ID     INTEGER,
    UNITS_SOLD INTEGER,
    CONSTRAINT fk_prod_id FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS (PROD_ID),
    CONSTRAINT fk_time_id FOREIGN KEY (TIME_ID) REFERENCES TIMES (TIME_ID),
    CONSTRAINT fk_loc_id FOREIGN KEY (LOC_ID) REFERENCES LOCATIONS (LOC_ID)
);

-- ADDING DATA TO TIMES TABLE
INSERT ALL INTO TIMES (TIME_ID, YEAR, QUARTER, MONTH, WEEK, DAY, HOLIDAY_FLAG)
VALUES (1, 2015, 4, 'OCTOBER', 2, 29, 0)
INTO TIMES
VALUES (2, 2015, 4, 'NOVEMBER', 1, 17, 0)
INTO TIMES
VALUES (3, 2016, 2, 'JUNE', 3, 30, 1)
INTO TIMES
VALUES (4, 2018, 2, 'APRIL', 1, 14, 0)
INTO TIMES
VALUES (5, 2020, 3, 'JULY', 4, 1, 1)
SELECT *
FROM DUAL;

SELECT *
FROM TIMES;


-- ADDING DATA TO LOCATIONS TABLE
INSERT ALL INTO LOCATIONS (LOC_ID, COUNTRY, STATE, CITY)
VALUES (1, 'IN', 'DLH', 'DELHI')
INTO LOCATIONS
VALUES (2, 'USA', 'NYC', 'NEW YORK')
INTO LOCATIONS
VALUES (3, 'IN', 'MUM', 'MAHARASHTRA')
INTO LOCATIONS
VALUES (4, 'CN', 'TOR', 'ONTARIO')
INTO LOCATIONS
VALUES (5, 'UK', 'LON', 'LONDON')
SELECT *
FROM DUAL;

SELECT *
FROM LOCATIONS;

-- ADDING DATA TO PRODUCTS TABLE
INSERT ALL INTO PRODUCTS (PROD_ID, PROD_NAME, CATEGORY, PRICE)
VALUES (1, 'SWEATER', 'WINTER WEAR', 400)
INTO PRODUCTS
VALUES (2, 'PEN', 'STATIONERY', 20)
INTO PRODUCTS
VALUES (3, 'ERASER', 'STATIONERY', 10)
INTO PRODUCTS
VALUES (4, 'GLOVES', 'WINTER WEAR', 150)
INTO PRODUCTS
VALUES (5, 'LUBRICANT', 'HOUSEHOLD', 100)
SELECT *
FROM DUAL;

SELECT *
FROM PRODUCTS;


-- ADDING RANDOM DATA TO SALES TABLE
INSERT ALL INTO SALES (PROD_ID, TIME_ID, LOC_ID, UNITS_SOLD)
VALUES (1, 1, 1, 6000)
INTO SALES
VALUES (2, 2, 2, 12000)
INTO SALES
VALUES (3, 3, 3, 4500)
INTO SALES
VALUES (4, 4, 4, 7600)
INTO SALES
VALUES (5, 5, 5, 10000)
SELECT *
FROM DUAL;

SELECT *
FROM SALES;
