-- CREATING A SIMPLE (BTREE) INDEX ON EMP
SELECT *
FROM EMP;

CREATE INDEX XX_BTREE_EMPNO_INDX ON EMP (EMPNO ASC, JOB DESC);

SELECT EMPNO
FROM EMP;

SELECT *
FROM EMP
WHERE EMPNO = 7369;

EXPLAIN PLAN FOR
(SELECT *
 FROM EMP
 WHERE EMPNO = 7639);

SELECT *
FROM TABLE ( DBMS_XPLAN.DISPLAY );

DROP INDEX XX_BTREE_EMPNO_INDX;

-- CREATING A UNIQUE INDEX ON EMP
SELECT *
FROM EMP;

EXPLAIN PLAN FOR
(SELECT *
 FROM EMP
 WHERE EMPNO = 7639);
SELECT *
FROM TABLE ( DBMS_XPLAN.DISPLAY );

CREATE UNIQUE INDEX XX_UNIQUE_MOBNUM_INDX ON EMP (MOBNUM);

EXPLAIN PLAN FOR
(SELECT *
 FROM EMP
 WHERE MOBNUM = 77986);
SELECT *
FROM TABLE ( DBMS_XPLAN.DISPLAY );

DROP INDEX XX_UNIQUE_MOBNUM_INDX;

-- CREATING A COMPOSITE INDEX ON EMP
SELECT *
FROM EMP;

EXPLAIN PLAN FOR
(SELECT *
 FROM EMP
 WHERE JOB IN ('SALESMAN', 'CLERK')
   AND DEPTNO = 10);
SELECT *
FROM TABLE ( DBMS_XPLAN.DISPLAY );

CREATE INDEX XX_COMP_INDX ON EMP (JOB, DEPTNO);

EXPLAIN PLAN FOR
(SELECT *
 FROM EMP
 WHERE JOB IN ('SALESMAN', 'CLERK')
   AND DEPTNO = 10);
SELECT *
FROM TABLE ( DBMS_XPLAN.DISPLAY );

-- CREATE A INDEX ORGANIZED TABLE ON EMP TABLE
CREATE TABLE EMP_IOT
(
    EMPNO    NUMBER(4) NOT NULL PRIMARY KEY,
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(9),
    MGR      NUMBER(4),
    HIREDATE DATE,
    SAL      NUMBER(7, 2),
    COMM     NUMBER(7, 2),
    DEPTNO   NUMBER(2)
)
    ORGANIZATION INDEX
    TABLESPACE USERS
    PCTTHRESHOLD 20
    OVERFLOW
    TABLESPACE USERS;

EXPLAIN PLAN FOR
(SELECT *
 FROM EMP_IOT
 WHERE EMPNO = 7369);

SELECT *
FROM TABLE ( DBMS_XPLAN.DISPLAY );

-- CREATE A BITMAP JOIN INDEX ON EMP TABLE
CREATE BITMAP INDEX XX_BITMAP_JOIN_INDX ON EMP E (E.DEPTNO) FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO;