SELECT *
FROM SALES;

SELECT *
FROM SALES
ORDER BY CONTINENT, COUNTRY, CITY;

-- LEAST GENERALISED CONCEPT IN THE CONCEPT HIERARCHY
SELECT CONTINENT, SUM(UNITS_SOLD)
FROM SALES
GROUP BY CONTINENT;

-- MID GENERALISED CONCEPT IN THE CONCEPT HIERARCHY
SELECT COUNTRY, SUM(UNITS_SOLD)
FROM SALES
GROUP BY COUNTRY;

-- MOST GENERALISED CONCEPT IN THE CONCEPT HIERARCHY
SELECT CITY, SUM(UNITS_SOLD)
FROM SALES
GROUP BY CITY;


-- NOW LET'S SEE HOW ALL THESE THREE QUERIES CAN BE COMBINED TO GIVE RESULTS
-- GROUPING SETS
SELECT CONTINENT, COUNTRY, CITY, SUM(UNITS_SOLD)
FROM SALES
GROUP BY GROUPING SETS ( CONTINENT, COUNTRY, CITY );


-- USING ROLLUP TO MIMIC THE ABOVE QUERY
SELECT CONTINENT, COUNTRY, CITY, SUM(UNITS_SOLD)
FROM SALES
GROUP BY ROLLUP ( CONTINENT, COUNTRY, CITY );
-- THIS WILL FIRST COMPUTE A GROUP BY ALL, SUM OF ALL.
-- NEXT IT WILL COMPUTE A GROUP BY OF ALL COMBINATIONS OF CONTINENTS, COUNTRY AND CITY.
-- NEXT IT WILL COMPUTE A GROUP BY OF ALL COMBINATIONS OF CONTINENTS AND COUNTRY.
-- NEXT IT WILL COMPUTE A GROUP BY CONTINENTS.

-- CUBE GIVES MORE FLEXIBILITY, IT GIVES COMBINATIONS OF ALL SETS
-- CONTINENT, COUNTRY, CITY -> CONTINENT, COUNTRY -> CONTINENT
-- COUNTRY, CITY -> COUNTRY
-- CONTINENT, CITY -> CITY
SELECT CONTINENT, COUNTRY, CITY, SUM(UNITS_SOLD)
FROM SALES
GROUP BY CUBE ( CONTINENT, COUNTRY, CITY );


DROP TABLE SALES;