CREATE TABLE SALES
(
    CONTINENT  VARCHAR(32),
    COUNTRY    VARCHAR(32),
    CITY       VARCHAR(32),
    UNITS_SOLD NUMBER(5)
);

INSERT ALL INTO SALES
VALUES ('NORTH AMERICA', 'CANADA', 'TORONTO', 10000)
INTO SALES
VALUES ('NORTH AMERICA', 'CANADA', 'MONTREAL', 5000)
INTO SALES
VALUES ('NORTH AMERICA', 'CANADA', 'VANCOUVER', 15000)
INTO SALES
VALUES ('ASIA', 'CHINA', 'HONG KONG', 7000)
INTO SALES
VALUES ('ASIA', 'CHINA', 'SHANGHAI', 3000)
INTO SALES
VALUES ('ASIA', 'JAPAN', 'TOKYO', 5000)
INTO SALES
VALUES ('EUROPE', 'UK', 'LONDON', 6000)
INTO SALES
VALUES ('EUROPE', 'UK', 'MANCHESTER', 12000)
INTO SALES
VALUES ('EUROPE', 'FRANCE', 'PARIS', 5000)
SELECT *
FROM DUAL;